print("Hello World")
print(2 + 3)
print("2 + 3 = ", 2 + 3)
print("I am just testing code")
print("اردو شاعری کا حسن")
print("subtract 10 from 20 =", 20 - 10)
print("multiply 2 by 3 =", 2 * 3)
print("modules of 10 and 5 =", 10 % 5)
print("first task")
print("python by codanics")
